<a href="https://colab.research.google.com/github/sri67ram/Inceptez_datascience/blob/main/Ex_2_Regiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
raw_data =  {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'],
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}

Step 2. Create the DataFrame with the following values:

Step 3. Assign it to a variable called regiment.

In [ ]:
regiment = pd.DataFrame(raw_data)

In [ ]:
regiment.head()

Step 4. What is the mean preTestScore from the regiment Nighthawks?

In [ ]:
regiment_pretestscore=regiment.groupby(['regiment'])['preTestScore'].mean()
regiment_pretestscore.Nighthawks

np.float64(15.25)

Step 5. Present general statistics by company

In [ ]:
regiment.groupby(['company']).describe()

        preTestScore                                                      \
               count       mean        std  min   25%   50%    75%   max
company
1st              6.0   6.666667   8.524475  2.0  3.00   3.5   4.00  24.0
2nd              6.0  15.500000  14.652645  2.0  2.25  13.5  29.25  31.0

        postTestScore
                count       mean        std   min    25%   50%   75%   max
company
1st               6.0  57.666667  27.485754  25.0  34.25  66.0  70.0  94.0
2nd               6.0  67.000000  14.057027  57.0  58.25  62.0  68.0  94.0

Step 6. What is the mean of each company's preTestScore?

In [ ]:
regiment.groupby(['company'])['preTestScore'].mean()

company
1st     6.666667
2nd    15.500000
Name: preTestScore, dtype: float64

Step 7. Present the mean preTestScores grouped by regiment and company

In [ ]:
regiment.groupby(['regiment','company'])['preTestScore'].mean()

regiment    company
Dragoons    1st         3.5
            2nd        27.5
Nighthawks  1st        14.0
            2nd        16.5
Scouts      1st         2.5
            2nd         2.5
Name: preTestScore, dtype: float64

Step 8. Present the mean preTestScores grouped by regiment and company without heirarchical indexing

In [ ]:
regiment.groupby(['regiment','company'])['preTestScore'].mean().reset_index()

     regiment company  preTestScore
0    Dragoons     1st           3.5
1    Dragoons     2nd          27.5
2  Nighthawks     1st          14.0
3  Nighthawks     2nd          16.5
4      Scouts     1st           2.5
5      Scouts     2nd           2.5

Step 9. Group the entire dataframe by regiment and company

In [ ]:
grouped=regiment.groupby(['regiment','company'])

In [ ]:
grouped.head()

      regiment company      name  preTestScore  postTestScore
0   Nighthawks     1st    Miller             4             25
1   Nighthawks     1st  Jacobson            24             94
2   Nighthawks     2nd       Ali            31             57
3   Nighthawks     2nd    Milner             2             62
4     Dragoons     1st     Cooze             3             70
5     Dragoons     1st     Jacon             4             25
6     Dragoons     2nd    Ryaner            24             94
7     Dragoons     2nd      Sone            31             57
8       Scouts     1st     Sloan             2             62
9       Scouts     1st     Piger             3             70
10      Scouts     2nd     Riani             2             62
11      Scouts     2nd       Ali             3             70

Step 10. What is the number of observations in each regiment and company

In [ ]:
regiment.groupby(['regiment','company']).count()

                    name  preTestScore  postTestScore
regiment   company
Dragoons   1st         2             2              2
           2nd         2             2              2
Nighthawks 1st         2             2              2
           2nd         2             2              2
Scouts     1st         2             2              2
           2nd         2             2              2

Step 11. Iterate over a group and print the name and the whole data from the regiment

In [ ]:
grouped=regiment.groupby(['regiment'])
grouped.head()

In [ ]:
for group_name, df_group in grouped:
    print(f"Group Name: {group_name}")
    print(df_group)
    print("-" * 30)

Group Name: ('Dragoons',)
   regiment company    name  preTestScore  postTestScore
4  Dragoons     1st   Cooze             3             70
5  Dragoons     1st   Jacon             4             25
6  Dragoons     2nd  Ryaner            24             94
7  Dragoons     2nd    Sone            31             57
------------------------------
Group Name: ('Nighthawks',)
     regiment company      name  preTestScore  postTestScore
0  Nighthawks     1st    Miller             4             25
1  Nighthawks     1st  Jacobson            24             94
2  Nighthawks     2nd       Ali            31             57
3  Nighthawks     2nd    Milner             2             62
------------------------------
Group Name: ('Scouts',)
   regiment company   name  preTestScore  postTestScore
8    Scouts     1st  Sloan             2             62
9    Scouts     1st  Piger             3             70
10   Scouts     2nd  Riani             2             62
11   Scouts     2nd    Ali             3             70
------------------------------